[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "10"
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=7200, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/admin"
  [headers.values]
    script = "<https://identity.netlify.com/v1/netlify-identity-widget.js> async defer"