[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "10"
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=720, must-revalidate"
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "private, no-cache, no-store, must-revalidate"
[[headers]]
  for = "/admin"
  [headers.values]
    script = "<https://identity.netlify.com/v1/netlify-identity-widget.js> async defer"