[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "10"
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"