backend:
  name: git-gateway
  repo: ThinkTechSN/luxaxess
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  # service collection
  - name: "service"
    label: "Services"
    label_singular: "Service"
    description: >
      This is where you list your services
    folder: "contents/services"
    slug: "{{title}}"
    delete: false
    create: true
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", tagname: "h2"}
      - {label: "Cover Image", name: "image", widget: "image"}
      - {label: "Content", name: "content", widget: "markdown"}
  
      # faq collection
  - name: "faq"
    label: "FAQ"
    description: >
      This is where you list frequent questions from your customers
    folder: "content/faq"
    create: true
    fields:
      - {label: "Question", name: "title", widget: "string", tagname: "h1"}
      - {label: "Answer", name: "body", widget: "markdown"}
  
      # settings collection
  - name: "settings"
    label: "Settings"
    description: >
      This is where is your site settings
    delete: false
    editor:
      preview: false
    files:
      - name: "settings"
        label: "Business Settings"
        file: "content/settings.json"
        description: "Business Settings"
        fields:
          - {label: "Busines name", name: "site", widget: "string"}
          - {label: "Busines description", name: "description", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Tel", name: "tel", widget: "string"}