backend:
  name: git-gateway
  repo: ThinkTechSN/luxaxess
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  # service collection
  - name: "service"
    label: "Services"
    label_singular: "Service"
    description: >
      This is where you list your services
    folder: "content/services"
    slug: "{{title}}"
    delete: false
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", tagname: "h2"}
      - {label: "Cover Image", name: "image", widget: "image"}
      - {label: "Content", name: "content", widget: "markdown"}

  # activity collection
  - name: "activity"
    label: "Activities"
    label_singular: "Activity"
    description: >
      This is where you list your activities related to a service
    folder: "content/activities"
    slug: "{{title}}"
    delete: false
    format: 'json'
    fields:
      - label: "Service"
        name: "service"
        widget: "relation"
        collection: "service"
        searchFields: ["title", "description"]
        valueField: "title"
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", tagname: "h2"}
      - {label: "Cover Image", name: "image", widget: "image"}
      - {label: "Content", name: "content", widget: "markdown"}

  # product collection
  - name: "product"
    label: "Products"
    label_singular: "Products"
    description: >
      This is where you list your products related to an activity
    folder: "content/products"
    slug: "{{title}}"
    create: true
    format: 'json'
    fields:
      - label: "Activity"
        name: "activity"
        widget: "relation"
        collection: "activity"
        searchFields: ["title", "description"]
        valueField: "title"
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", tagname: "h2"}
      - {label: "Cover Image", name: "image", widget: "image"}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "Price", name: "price", widget: "number"}
  
  # cms collection
  - name: "cms"
    label: "Content management"
    label_singular: "Content"
    description: >
      This is where you list manage your site content
    slug: "{{title}}"
    delete: false
    files:
      - name: "about"
        label: "About Luxaxes"
        file: "content/cms/about.json"
        description: "About page"
        fields:
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Description", name: "description", widget: "text", tagname: "h2"}
          - {label: "Cover Image", name: "image", widget: "image"}
          - {label: "Content", name: "content", widget: "markdown"}
      - name: "brochure"
        label: "Our brochure"
        file: "content/cms/brochure.json"
        description: "Brochure page"
        fields:
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Description", name: "description", widget: "text", tagname: "h2"}
          - {label: "Cover Image", name: "image", widget: "image"}
          - {label: "Content", name: "content", widget: "markdown"}
      - name: "faq"
        label: "FAQ"
        description: >
          This is where you list frequent questions from your customers
        file: "content/cms/faq.json"
        create: true
        fields:
          - {label: "Question", name: "title", widget: "string", tagname: "h1"}
          - {label: "Answer", name: "body", widget: "markdown"}
      - name: "sav"
        label: "SAV"
        file: "content/cms/sav.json"
        description: "SAV page"
        fields:
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Description", name: "description", widget: "text", tagname: "h2"}
          - {label: "Cover Image", name: "image", widget: "image"}
          - {label: "Content", name: "content", widget: "markdown"}
      - name: "conditions"
        label: "Conditions"
        file: "content/cms/conditions.json"
        description: "Sale Conditions page"
        fields:
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Description", name: "description", widget: "text", tagname: "h2"}
          - {label: "Cover Image", name: "image", widget: "image"}
          - {label: "Content", name: "content", widget: "markdown"}
      - name: "termes"
        label: "Terms"
        file: "content/cms/terms.json"
        description: "Terms page"
        fields:
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Description", name: "description", widget: "text", tagname: "h2"}
          - {label: "Cover Image", name: "image", widget: "image"}
          - {label: "Content", name: "content", widget: "markdown"}
  
      # settings collection
  - name: "settings"
    label: "Settings"
    description: >
      This is where is your site settings
    delete: false
    editor:
      preview: false
    files:
      - name: "settings"
        label: "Business Settings"
        file: "content/settings.json"
        description: "Business Settings"
        fields:
          - {label: "Busines name", name: "site", widget: "string"}
          - {label: "Busines description", name: "description", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Tel", name: "tel", widget: "string"}
          - {label: "Cover Image", name: "image", widget: "image"}
          - {label: "Cover Text", name: "content", widget: "string"}